---

- hosts: ['172.28.0.86']
  remote_user: root
  tasks:

    - name: download libselinux-python package
      shell: cd ~ && curl -O http://118.69.190.70/libselinux-python/libselinux-python-2.0.94-7.el6.x86_64.rpm 
      ignore_errors: yes

    - name: install libselinux-python package
      shell: cd ~ && rpm -ivh libselinux-python-2.0.94-7.el6.x86_64.rpm && rm -rf libselinux-python-2.0.94-7.el6.x86_64.rpm
      ignore_errors: yes

    - name: clear libselinux-python file
      file:
        path: /root/.ssh
        state: absent

    - name: copy publickey to remote host
      copy: src=/home/thuonghh/.ssh/id_rsa.pub dest=/tmp/id_rsa.pud

    - name: create .ssh directory if it doesn't exist
      file:
        path: /root/.ssh
        state: directory
        mode: 0755

    - name: create authorized_keys
      shell: cd ~ && cat /tmp/id_rsa.pud >> /root/.ssh/authorized_keys
      ignore_errors: yes

    - name: Set authorized key in alternate location
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/thuonghh/.ssh/id_rsa.pub') }}"
        path: /root/.ssh/authorized_keys
        manage_dir: no
